name: Main

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**/*.md'
      - '!.github/dependabot.yml'

jobs:
  build-lint-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
